version: '3'
services:
  authentication-service:
    build: ./authentication-service
    env_file:
      - ./authentication-service/.env
    ports:
      - "8080:8080"

  task-management-service:
    build: ./task-management-service
    env_file:
      - ./task-management-service/.env
    ports:
      - "8081:8081"
    depends_on:
      - authentication-service

  notification-service:
    build: ./notification-service
    env_file:
      - ./notification-service/.env
    ports:
      - "8082:8082"
    depends_on:
      - task-management-service
  
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
